### PR TITLE
Perform SIGTERM handling and upgrade redis, python, honcho

### LINKED ISSUE #1: Pressing Ctrl + C does not terminate the docker container in non-daemon mode
I know `docker stop` works. 
This will just be a good usability feature

### LINKED ISSUE #2: Redis upgrade
This image refers to `redis:latest` at the time when this was pushed to docker hub so its frozen in `3.2.3`.
Currently, The latest stable version of redis is `4.0.11`
The FROM part should refer to this instead of the latest and pushed to docker hub

### PR DESCRIPTION
**Pull request by kishaningithub**
- [x] Make honcho respond to SIGTERM. Fixes #1 
- [x] Explicitly specify redis version. Fixes #2 
- [x] Un buffer output of honcho. Refer [this issue](https://github.com/nickstenning/honcho/issues/136) in honcho repo
- [x] Use python 3 instead of python 2 for honcho

### CODE REVIEW

**Comment by madflojo** [comment]
@kishaningithub I'd like to keep it as `latest`, as soon as this PR is merged it will trigger an automatic build on DockerHub. 

Everything else looks like some good additions thanks for the contribution!

**Comment by kishaningithub** [comment]
@madflojo My concern is, If `redis` image is always pointing to the `latest` then there is no reason ever for the code to change so the automatic build will not be triggered whenever redis releases a new version. As for this case the last build was 2 years back.

I am not really sure if docker hub as a timely trigger and what if latest does not point to the latest stable version ?

I also read your excellent blog on [Using Travis CI to test Docker builds](https://bencane.com/2016/01/11/using-travis-ci-to-test-docker-builds/). Travis CI does have timely build triggers and we can test the `docker build` and `docker run` part

**Comment by kishaningithub** [comment]
@madflojo Also Isn't the latest tag considered an anti pattern ([Ref link](https://vsupalov.com/docker-latest-tag/)) ? 
Given that my humble opinion would be to move away from using the `latest` tag for `redis-tls` image and use `semver`. One approach for this would be to keep it same as that of redis version, the advantage of this is when i pull the image i know which redis version i am using in "tls mode"

**Comment by madflojo** [comment]
@kishaningithub to be honest, while that article has a lot of good points. The `latest` tag is pretty much a standard practice across Docker images. I wouldn't want to deviate from a standard practice that many projects follow.

I did however take a look at DockerHub and it looks like they have a feature that lets you trigger a build when another project is updated. I set this up for the `redis-tls` image.

image

I'm down with keeping in line with the Redis versioning scheme. A simple way to do this would be to create a new branch for each version that is mirrored, in that branch we could use the specific version. I'd rather keep `master` as `latest` though, as that tends to be the status quo.

I've gone ahead and created a `4.0.6` branch from master as it stands now. If you want to change this PR to `4.0.6` and then open another PR for `master`, I'd be down to merge.

**Comment by kishaningithub** [comment]
Have created the [PR](https://github.com/madflojo/redis-tls-dockerfile/pull/4) for `4.0.6`.

One question though, The current stable version of redis is `4.0.11`. Any specific reason to choose `4.0.6` "

**Comment by madflojo** [comment]
It’s the version I got when I did a latest pull for the main Redis image.

**Pull request merged**
